
CREATE SEQUENCE BRAND_ID_SEQ START WITH 1;
INSERT INTO Brand VALUES (BRAND_ID_SEQ.NEXTVAL ,'BMV');
INSERT INTO Brand VALUES (BRAND_ID_SEQ.NEXTVAL ,'AUDI');
INSERT INTO Brand VALUES (BRAND_ID_SEQ.NEXTVAL ,'VW');
INSERT INTO Brand VALUES (BRAND_ID_SEQ.NEXTVAL ,'OPEL');
INSERT INTO Brand VALUES (BRAND_ID_SEQ.NEXTVAL ,'FORD');
Select * FROM BRAND;
/
CREATE SEQUENCE MODEL_ID_SEQ START WITH 1000;
INSERT INTO MODEL VALUES (MODEL_ID_SEQ.NEXTVAL ,1, 'Q7');
INSERT INTO MODEL VALUES (MODEL_ID_SEQ.NEXTVAL ,2, 'WRONG INPUT');
INSERT INTO MODEL VALUES (MODEL_ID_SEQ.NEXTVAL ,3, 'Q5');
Select * FROM MODEL;
/
CREATE SEQUENCE TRANSMISSION_ID_SEQ START WITH 2000;
INSERT INTO TRANSMISSION VALUES (TRANSMISSION_ID_SEQ.NEXTVAL , 'AUTOMATIC');
INSERT INTO TRANSMISSION VALUES (TRANSMISSION_ID_SEQ.NEXTVAL , 'MANUAL');
INSERT INTO TRANSMISSION VALUES (TRANSMISSION_ID_SEQ.NEXTVAL , 'WRONG INPUT');
Select * FROM TRANSMISSION;
/
CREATE SEQUENCE FUEL_ID_SEQ START WITH 3000;
INSERT INTO FUEL VALUES (FUEL_ID_SEQ.NEXTVAL , 'GASOLINE');
INSERT INTO FUEL VALUES (FUEL_ID_SEQ.NEXTVAL , 'DIESEL');
INSERT INTO FUEL VALUES (FUEL_ID_SEQ.NEXTVAL , 'WRONG INPUT');
INSERT INTO FUEL VALUES (FUEL_ID_SEQ.NEXTVAL , 'HEAVY DUTY OIL');
Select * FROM FUEL;
/

CREATE SEQUENCE CAR_ID_SEQ START WITH 10000;
INSERT INTO CAR VALUES (CAR_ID_SEQ.NEXTVAL ,'WA1ECCFS6JR009012', 1001, 5700.00, '2020-05-13', 2002, 3002, 'BROKEN LEFT FRONT SEAT');
INSERT INTO CAR VALUES (CAR_ID_SEQ.NEXTVAL ,'1GNEK13T1XJ499256', 1003, 12300.00, '2000-05-13', 2004, 3001, '');
INSERT INTO CAR VALUES (CAR_ID_SEQ.NEXTVAL ,'ZEBRA', 01, -5700.00, '2024-05-13', 2002, 3002, 'BROKEN LEFT FRONT SEAT');

Select * FROM CAR;
