create table BRAND
(
    BRAND_ID          BIGINT generated by default as identity,
    NAME      VARCHAR2 not null,
    constraint "BRAND_PK" primary key (BRAND_ID)
);

/
create table MODEL
(
    MODEL_ID          BIGINT generated by default as identity,
    BRAND_ID          BIGINT not null,
    NAME      VARCHAR2(17) not null,
    constraint "MODEL_PK" primary key (MODEL_ID),
    constraint "MODEL_BRAND_FK"
        foreign key (BRAND_ID) references BRAND (BRAND_ID)
);
/
create table TRANSMISSION
(
    TRANSMISSION_ID          BIGINT generated by default as identity,
    NAME      VARCHAR2(17) not null,
    constraint "TRANSMISSION_PK" primary key (TRANSMISSION_ID)
);
/
create table FUEL
(
    FUEL_ID          BIGINT generated by default as identity,
    NAME      VARCHAR2(17) not null,
    constraint "FUEL_PK" primary key (FUEL_ID)
);
/
create table CAR
(
    CAR_ID          BIGINT generated by default as identity,
    VIN_NUMBER      VARCHAR2(17) not null,
    MODEL_ID        BIGINT   not null,
    PRICE           BIGINT   not null,
    REG_DATE        DATE         not null,
    TRANSMISSION_ID BIGINT   not null,
    FUEL_ID         BIGINT   not null,
    REMARKD         VARCHAR2(255),
    constraint "CAR_PK"
        primary key (CAR_ID),
    constraint "CAR_FUEL_FK"
        foreign key (FUEL_ID) references FUEL (FUEL_ID),
    constraint "CAR_MODEL_FK"
        foreign key (MODEL_ID) references MODEL (MODEL_ID),
    constraint "CAR_TRANSMISSION_FK"
        foreign key (TRANSMISSION_ID) references TRANSMISSION (TRANSMISSION_ID)
);
